language: ruby
env:
  - JRUBY_OPTS=-Xcext.enabled=true
rvm:
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-18mode
    - rvm: jruby-19mode
notifications:
  email:
    - sferik@gmail.com
